export const sample_foods: any[] = [
  {
    id: '1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 600,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch']
  },
  {
    id: '2',
    name: 'Meatball',
    price: 900,
    cookTime: '20-30',
    favorite: false,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '3',
    name: 'Hamburger',
    price: 550,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '4',
    name: 'Fried Potatoes',
    price: 700,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.4,
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Fry']
  },
  {
    id: '5',
    name: 'Chicken Soup',
    price: 800,
    cookTime: '20-30',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '6',
    name: 'Vegetables Pizza',
    price: 650,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/pizza.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '7',
    name: 'Pasta',
    price: 850,
    cookTime: '40-50',
    favorite: true,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/pasta.jpg',
    tags: ['FastFood'],
  },
  {
    id: '8',
    name: 'Tacos',
    price: 750,
    cookTime: '30-40',
    favorite: true,
    origins: ['Mexico'],
    stars: 4.0,
    imageUrl: 'assets/tacos.jpg',
    tags: ['FastFood'],
  },
]
export const sample_tags:any[] = [
  { name: 'All', count: 8 },
  { name: 'FastFood', count: 6 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
]

export const sample_users: any[] = [
  {
    name: 'rinkal',
    email: 'rinkal@gmail.com',
    password: '12345',
    address: 'India',
    isAdmin: true,
  },
  {
    name: 'Jane Doe',
    email: 'Jane@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: false,
  },
];